  // ---------- styles: Panel shell, header, icon buttons, switches, resize handles ----------
  var cssPanel = [
    '#sk-enh-root *{box-sizing:border-box;}',
    '#sk-enh-root{position:fixed;z-index:2147483000;bottom:20px;right:20px;',
    'font-family:' + FONT + ';color:' + C.text + ';}',
    '#sk-enh-toggle{position:relative;z-index:2;width:52px;height:52px;border-radius:50%;background:' + C.panel + ';',
    'border:1px solid ' + C.line + ';color:' + C.amber + ';font-size:20px;cursor:pointer;box-shadow:0 4px 18px rgba(0,0,0,.5);',
    'display:flex;align-items:center;justify-content:center;font-family:"Courier New",monospace;letter-spacing:-1px;}',
    '#sk-enh-toggle:hover{border-color:' + C.amber + ';}',
    '#sk-enh-panel{position:fixed;z-index:1;background:' + C.panel + ';border:1px solid ' + C.line + ';',
    'box-shadow:0 12px 40px rgba(0,0,0,.6);display:flex;flex-direction:column;overflow:hidden;}',
    '#sk-enh-head{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;',
    'border-bottom:1px solid ' + C.line + ';background:' + C.panel2 + ';cursor:move;user-select:none;touch-action:none;}',
    '#sk-enh-head .brand{font-family:"Courier New",monospace;font-size:12px;color:' + C.dim + ';letter-spacing:1px;}',
    '#sk-enh-head .brand b{color:' + C.amber + ';}',
    '.sk-icon-btn{width:24px;border:1px solid ' + C.line + ';background:transparent;color:' + C.dim + ';display:flex;',
    'align-items:center;justify-content:center;cursor:pointer;font-size:13px;line-height:1;padding:0;',
    'font-family:inherit;}',
    '.sk-icon-btn:hover:not(:disabled){border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-icon-btn.active{background:' + C.amberDim + ';border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-icon-btn:disabled{opacity:.35;cursor:default;}',
    '.sk-toggle-row{display:flex;align-items:center;justify-content:space-between;padding:5px 1px;}',
    '.sk-toggle-label{font-size:12px;color:' + C.text + ';}',
    '.sk-mad-tag{font-size:10px;color:' + C.dim + ';font-weight:normal;font-style:italic;margin-left:2px;}',
    '.sk-dropzone{border:1.5px dashed ' + C.line + ';padding:14px 10px;text-align:center;font-size:12px;color:' + C.dim + ';',
    'cursor:pointer;transition:border-color .15s,background .15s,color .15s;}',
    '.sk-dropzone:hover{border-color:' + C.amber + ';color:' + C.text + ';}',
    '.sk-dropzone.is-dragover{border-color:' + C.amber + ';background:' + C.panel2 + ';color:' + C.text + ';}',
    '.sk-section-label{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:' + C.dim + ';margin:14px 0 8px;',
    'padding-top:10px;border-top:1px solid ' + C.line + ';}',
    '.sk-section-label:first-child{margin-top:0;padding-top:0;border-top:none;}',
    '.sk-subpanel{border-left:2px solid ' + C.line + ';padding:8px 0 2px 10px;margin:2px 0 10px;}',
    '.sk-subdivider{border-top:1px solid ' + C.line + ';margin:10px 0;padding-top:10px;}',
    '.sk-toggle-switch{position:relative;width:32px;height:17px;border-radius:9px;flex-shrink:0;background:' + C.line + ';',
    'cursor:pointer;transition:background .15s ease;}',
    '.sk-toggle-switch.active{background:' + C.amberDim + ';}',
    '.sk-toggle-knob{position:absolute;top:2px;left:2px;width:13px;height:13px;border-radius:50%;background:' + C.dim + ';',
    'transition:left .15s ease,background .15s ease;}',
    '.sk-toggle-switch.active .sk-toggle-knob{left:17px;background:' + C.amber + ';}',
    '.sk-resize-corner{position:absolute;width:14px;height:14px;z-index:5;touch-action:none;}',
    '.sk-resize-corner.nw{top:0;left:0;cursor:nwse-resize;}',
    '.sk-resize-corner.ne{top:0;right:0;cursor:nesw-resize;}',
    '.sk-resize-corner.sw{bottom:0;left:0;cursor:nesw-resize;}',
    '#sk-enh-resize-se{position:absolute;right:0;bottom:0;width:16px;height:16px;cursor:nwse-resize;',
    'touch-action:none;z-index:5;',
    'background:linear-gradient(135deg,transparent 0 40%,' + C.dim + ' 40% 46%,transparent 46% 58%,' + C.dim + ' 58% 64%,transparent 64% 100%);',
    'opacity:.7;}',
    '#sk-enh-resize-se:hover{opacity:1;}',
    '.sk-resize-edge{position:absolute;z-index:4;touch-action:none;}',
    '.sk-resize-edge.n{top:0;left:14px;right:14px;height:6px;cursor:ns-resize;}',
    '.sk-resize-edge.s{bottom:0;left:14px;right:14px;height:6px;cursor:ns-resize;}',
    '.sk-resize-edge.w{left:0;top:14px;bottom:14px;width:6px;cursor:ew-resize;}',
    '.sk-resize-edge.e{right:0;top:14px;bottom:14px;width:6px;cursor:ew-resize;}',
  ];
