  // ---------- styles: Mode switch, show picker, frequency lists, episode grid ----------
  var cssShows = [
    '.sk-mode-row{display:flex;}',
    '.sk-mode-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.dim + ';cursor:pointer;font-family:inherit;',
    'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
    '.sk-mode-btn:hover{border-color:' + C.amber + ';}',
    '.sk-mode-btn.active{background:' + C.amberDim + ';border-color:' + C.amber + ';color:' + C.amber + ';font-weight:bold;}',
    '.sk-facet-grid{border:1px solid ' + C.line + ';padding:8px 8px 6px;background:' + C.bg + ';display:grid;',
    'grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:2px 10px;max-height:220px;overflow-y:auto;',
    'overflow-x:hidden;}',
    '.sk-caption{color:' + C.dim + ';font-size:10.5px;line-height:1.5;}',
    '.sk-show-pick{display:flex;justify-content:space-between;align-items:center;border:1px solid ' + C.line + ';',
    'cursor:pointer;}',
    '.sk-show-pick:hover{border-color:' + C.amber + ';background:' + C.panel2 + ';}',
    '.sk-show-pick .name{font-family:"Courier New",monospace;font-size:12px;}',
    '.sk-show-pick .cnt{color:' + C.dim + ';font-size:11px;}',
    '.sk-show-pick.off{opacity:.5;cursor:default;}',
    '.sk-show-pick.off:hover{border-color:' + C.line + ';background:none;}',
    '.sk-show-head{display:flex;align-items:center;flex-wrap:wrap;}',
    '.sk-mini-toggle{background:transparent;border:1px solid ' + C.line + ';color:' + C.dim + ';cursor:pointer;',
    'font-family:inherit;white-space:nowrap;}',
    '.sk-mini-toggle:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-show-head .title{font-size:15px;color:' + C.amber + ';font-family:"Courier New",monospace;}',
    '.sk-show-head a{font-size:11px;color:' + C.dim + ';text-decoration:none;}',
    '.sk-show-head a:hover{color:' + C.amber + ';}',
    '.sk-show-nav{display:flex;align-items:center;justify-content:space-between;}',
    '.sk-freq-list{border:1px solid ' + C.line + ';padding:10px 12px 6px;',
    'background:linear-gradient(180deg,' + C.panel2 + ',' + C.panel + ');}',
    '.sk-freq-row{display:flex;align-items:center;gap:8px;padding:4px 2px;cursor:pointer;',
    'transition:background .12s ease;}',
    '.sk-freq-row:hover{background:rgba(255,176,32,.08);}',
    '.sk-freq-row.is-show:hover{background:rgba(109,179,242,.08);}',
    '.sk-freq-rank{width:14px;flex-shrink:0;font-size:10px;color:' + C.dim + ';text-align:right;',
    'font-family:"Courier New",monospace;}',
    '.sk-freq-name{width:112px;flex-shrink:0;font-size:12px;color:' + C.amber + ';white-space:nowrap;overflow:hidden;',
    'text-overflow:ellipsis;}',
    '.sk-freq-row.is-show .sk-freq-name{color:' + C.link + ';}',
    '.sk-freq-bar-wrap{flex:1;height:6px;border-radius:3px;background:' + C.bg + ';overflow:hidden;}',
    '.sk-freq-bar{height:100%;border-radius:3px;background:linear-gradient(90deg,' + C.amberDim + ',' + C.amber + ');}',
    '.sk-freq-row.is-show .sk-freq-bar{background:linear-gradient(90deg,#2c5170,' + C.link + ');}',
    '.sk-freq-count{width:34px;flex-shrink:0;text-align:right;font-size:11px;color:' + C.dim + ';',
    'font-family:"Courier New",monospace;}',
    '.sk-nav-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';cursor:pointer;font-family:inherit;',
    'white-space:nowrap;}',
    '.sk-nav-btn:hover:not(:disabled){border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-nav-btn:disabled{opacity:.35;cursor:default;}',
    '.sk-nav-crumb{flex:1;text-align:center;font-size:11px;color:' + C.dim + ';font-family:"Courier New",monospace;',
    'overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-related-row{display:flex;flex-wrap:wrap;}',
    '.sk-chip.clickable{cursor:pointer;}',
    '.sk-chip.clickable:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-ep-grid{display:grid;grid-template-columns:repeat(3,1fr);}',
    '.sk-ep-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';padding:8px 4px;text-align:center;cursor:pointer;}',
    '.sk-ep-btn:hover{border-color:' + C.amber + ';}',
    '.sk-ep-btn .num{display:block;font-family:"Courier New",monospace;color:' + C.amber + ';font-size:13px;',
    'font-weight:bold;}',
    '.sk-ep-btn .cnt{display:block;font-size:10px;color:' + C.dim + ';margin-top:2px;}',
    // pool detail header: title and clip count on the left, the compact Export Clips button on the right
    '.sk-show-head .title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-show-head .meta{flex:0 0 auto;font-size:11px;color:' + C.dim + ';}',
    '.sk-show-head .sk-btn{margin-left:auto;flex:0 0 auto;}',
    // pools list rows: a three-clip preview strip beside the name and clip count
    '.sk-show-pick.sk-pool-row{justify-content:flex-start;gap:10px;}',
    '.sk-pool-row .thumbs{display:flex;gap:4px;flex:0 0 auto;}',
    '.sk-pool-row .thumbs img,.sk-pool-row .thumbs i{width:32px;height:32px;object-fit:cover;border-radius:' + R_INNER + ';',
    'background:' + C.panel2 + ';display:block;box-sizing:border-box;}',
    '.sk-pool-row .thumbs i{background:none;border:1px dashed ' + C.line + ';}',
    '.sk-pool-row .main{flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;}',
    '.sk-pool-row .name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-pool-row .sub{font-size:11px;color:' + C.dim + ';}',
    '.sk-pool-row .chev{flex:0 0 auto;color:' + C.dim + ';font-size:14px;}',
    '.sk-pool-row:hover .chev{color:' + C.amber + ';}',
  ];
