  // ---------- styles: Clip viewer and image viewer, login, comments, frame bar, trim and download rows ----------
  var cssViewer = [
    '.sk-close{cursor:pointer;color:' + C.dim + ';font-size:16px;line-height:1;}',
    '.sk-media-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:2147483600;display:flex;',
    'align-items:center;justify-content:center;padding:24px;}',
    '.sk-media-box{max-width:760px;width:100%;max-height:90vh;background:' + C.panel + ';border:1px solid ' + C.line + ';',
    'overflow-y:auto;overflow-x:hidden;box-shadow:0 20px 60px rgba(0,0,0,.6);}',
    '.sk-media-box video,.sk-media-box img{width:100%;max-height:72vh;display:block;background:#000;',
    'object-fit:contain;}',
    '.sk-media-top{position:sticky;top:0;z-index:1;display:flex;align-items:center;gap:8px;padding:8px 10px;',
    'background:' + C.panel2 + ';}',
    // right-hand group of the viewer's top bar: the booru link, then the two actions — one size, one baseline
    '.sk-media-actions{margin-left:auto;display:flex;align-items:center;flex-wrap:wrap;justify-content:flex-end;gap:6px 14px;}',
    '.sk-media-viewpost,.sk-media-act{display:inline-flex;align-items:center;height:24px;margin:0;padding:0;',
    'font-family:"Courier New",monospace;font-size:12px;line-height:1;text-decoration:none;white-space:nowrap;cursor:pointer;}',
    '.sk-media-act{color:' + C.amber + ';}',
    '.sk-media-act:hover{text-decoration:underline;}',
    '.sk-media-viewpost{color:' + C.booru + ';}',
    '.sk-media-viewpost:hover{color:' + C.booruHover + ';text-decoration:underline;}',
    '.sk-media-close{cursor:pointer;color:' + C.dim + ';font-size:22px;line-height:1;padding:0 2px 2px;}',
    '.sk-login-box{width:100%;max-width:320px;background:' + C.panel + ';border:1px solid ' + C.line + ';padding:18px;',
    'box-shadow:0 20px 60px rgba(0,0,0,.6);}',
    '.sk-login-title{font-size:15px;font-weight:bold;color:' + C.text + ';margin-bottom:12px;}',
    '.sk-login-box .sk-input{width:100%;margin-bottom:8px;}',
    '.sk-login-cancel{display:block;text-align:center;margin-top:10px;color:' + C.dim + ';font-size:12px;cursor:pointer;}',
    '.sk-comment-composer{background:' + C.panel2 + ';border:1px solid ' + C.line + ';padding:8px;margin-bottom:10px;}',
    '.sk-comment-loggedin{display:flex;justify-content:space-between;font-size:11px;color:' + C.dim + ';margin-bottom:6px;}',
    '.sk-comment-logout{color:' + C.red + ';cursor:pointer;}',
    '.sk-comment-textarea{width:100%;background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';padding:6px;',
    'font-size:12px;min-height:50px;resize:vertical;margin-bottom:6px;font-family:inherit;}',
    '.sk-comment-loginlink{color:' + C.amber + ';font-size:12px;font-weight:600;cursor:pointer;margin-bottom:10px;',
    'display:inline-block;}',
    '.sk-media-close:hover{color:' + C.red + ';}',
    '.sk-frame-bar{padding:8px 10px;background:' + C.panel2 + ';border-top:1px solid ' + C.line + ';}',
    '.sk-frame-row{display:flex;align-items:center;gap:4px;}',
    '.sk-frame-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';font-size:13px;cursor:pointer;',
    'font-family:inherit;white-space:nowrap;}',
    '.sk-frame-btn:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-frame-count{flex:1;text-align:center;font-size:13px;font-weight:bold;color:' + C.amber + ';',
    'font-family:"Courier New",monospace;}',
    '.sk-frame-time{text-align:center;font-size:11px;color:' + C.dim + ';margin-top:5px;',
    'font-family:"Courier New",monospace;}',
    '.sk-trim-row{display:flex;align-items:center;gap:6px;padding:8px 10px 0;flex-wrap:wrap;}',
    '.sk-trim-label{font-size:10px;color:' + C.dim + ';font-family:"Courier New",monospace;}',
    '.sk-action-row{display:flex;gap:6px;padding:8px 10px;}',
    '.sk-action-row .sk-frame-btn{flex:1;}',
    '.sk-frame-btn:disabled{opacity:.35;cursor:default;}',
    '.sk-frame-btn:disabled:hover{border-color:' + C.line + ';color:' + C.text + ';}',
    '.sk-action-status{padding:0 10px 8px;font-size:11px;color:' + C.amber + ';font-family:"Courier New",monospace;',
    'min-height:14px;}',
    '.sk-load-more-wrap{text-align:center;}',
    '.sk-load-more-wrap .sk-frame-btn{display:inline-block;padding:8px 16px;}',
    '.sk-comments-row{padding:0 10px 8px;border-top:1px solid ' + C.line + ';padding-top:8px;}',
    '.sk-comments-panel{max-height:220px;overflow-y:auto;padding:0 10px 10px;}',
    '.sk-comment{padding:8px 0;border-top:1px solid ' + C.line + ';}',
    '.sk-comment:first-child{border-top:none;}',
    '.sk-comment-head{display:flex;justify-content:space-between;font-size:11px;color:' + C.amber + ';',
    'font-family:"Courier New",monospace;margin-bottom:3px;}',
    '.sk-comment-head span{color:' + C.dim + ';font-weight:normal;}',
    '.sk-comment-body{font-size:12px;color:' + C.text + ';line-height:1.5;white-space:pre-wrap;}',
    '.sk-comment-quote{border-left:3px solid ' + C.line + ';padding:4px 0 4px 8px;margin:4px 0;color:' + C.dim + ';}',
    '.sk-comment-ts{color:' + C.amber + ';cursor:pointer;font-weight:bold;}',
    '.sk-comment-ts:hover{text-decoration:underline;}',
    '.sk-comment-postlink{color:' + C.link + ';cursor:pointer;text-decoration:underline;}',
    '.sk-comment-link{color:' + C.booru + ';text-decoration:underline;}',
    '.sk-close:hover{color:' + C.red + ';}',
  ];
