  // ---------- styles: Info badges, stars, tag chips and the exclude-tags filter ----------
  var cssTags = [
    '.sk-dock-head{display:flex;align-items:center;justify-content:space-between;padding:8px 10px;background:' + C.panel2 + ';',
    'border-bottom:1px solid ' + C.line + ';}',
    '.sk-dock-badges{display:flex;gap:6px;align-items:center;}',
    '.sk-badge{font-family:"Courier New",monospace;font-size:11px;padding:2px 7px;background:' + C.bg + ';',
    'border:1px solid ' + C.line + ';color:' + C.text + ';}',
    '.sk-badge.score{color:' + C.amber + ';border-color:' + C.amberDim + ';}',
    '.sk-stars{display:inline-flex;gap:2px;align-items:center;}',
    '.sk-star{font-size:15px;color:' + C.dim + ';cursor:pointer;line-height:1;}',
    '.sk-star.filled{color:' + C.amber + ';}',
    '.sk-star-clear{font-size:12px;color:' + C.dim + ';cursor:pointer;margin-left:3px;opacity:.3;}',
    '.sk-star-clear.active{opacity:.8;}',
    '.sk-star-clear:hover{color:' + C.red + ';opacity:1;}',
    '.sk-dock-head a{font-size:11px;color:' + C.amber + ';text-decoration:none;border:1px solid ' + C.amberDim + ';padding:2px 8px;}',
    '.sk-dock-head a:hover{background:' + C.amberDim + ';}',
    '.sk-dock-body{padding:10px;}',
    '.sk-dock-section + .sk-dock-section{margin-top:9px;}',
    '.sk-tagblock-label{color:' + C.dim + ';font-size:10px;text-transform:uppercase;letter-spacing:.6px;margin:0 0 5px;',
    'display:flex;align-items:center;gap:5px;}',
    '.sk-tagblock-label:before{content:"";width:3px;height:3px;border-radius:50%;background:' + C.dim + ';',
    'display:inline-block;}',
    '.sk-chipwrap{display:flex;flex-wrap:wrap;gap:5px;max-height:110px;overflow-y:auto;}',
    '.sk-mini-chip{display:inline-block;font-size:10px;margin:0 4px 4px 0;font-family:"Courier New",monospace;',
    'border:1px solid ' + C.line + ';background:' + C.panel2 + ';}',
    '.sk-mini-chip.artist{background:' + C.amberDim + ';border-color:' + C.amber + ';color:' + C.amber + ';font-weight:bold;}',
    '.sk-mini-chip.other{color:' + C.dim + ';}',
    '.sk-mini-chip.show{color:' + C.link + ';}',
    '.sk-mini-chip.clickable{cursor:pointer;}',
    '.sk-mini-chip.clickable:hover{border-color:' + C.amber + ';}',
    '.sk-facet-item{display:flex;align-items:center;gap:5px;font-size:11px;padding:4px 2px;cursor:pointer;',
    'color:' + C.text + ';min-width:0;}',
    '.sk-facet-item:hover{background:' + C.panel2 + ';}',
    '.sk-facet-item.off{color:' + C.dim + ';text-decoration:line-through;opacity:.6;}',
    '.sk-facet-item input{accent-color:' + C.amber + ';flex-shrink:0;width:13px;height:13px;margin:0;}',
    '.sk-facet-item .fname{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;',
    'font-family:"Courier New",monospace;}',
    '.sk-facet-item .fcount{flex-shrink:0;color:' + C.dim + ';font-family:"Courier New",monospace;font-size:10px;}',
    '.sk-facet-item.is-artist .fname{color:' + C.amber + ';font-weight:bold;}',
    '.sk-filter-toggle{gap:6px;background:transparent;border:1px solid ' + C.line + ';color:' + C.text + ';cursor:pointer;',
    'font-family:inherit;}',
    '.sk-filter-toggle:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-filter-toggle .chev{font-size:8px;color:' + C.dim + ';transition:transform .15s ease;}',
    '.sk-filter-toggle.open .chev{transform:rotate(180deg);}',
    '.sk-filter-badge{background:' + C.amberDim + ';color:' + C.amber + ';padding:0 6px;font-family:"Courier New",monospace;',
    'font-size:10px;line-height:1.5;}',
  ];
