  var css = [
    '#sk-enh-root *{box-sizing:border-box;}',
    '#sk-enh-root{position:fixed;z-index:2147483000;bottom:20px;right:20px;',
    'font-family:"Neue Haas Grotesk","Helvetica Neue",Arial,sans-serif;color:' + C.text + ';}',
    '#sk-enh-toggle{position:relative;z-index:2;width:52px;height:52px;border-radius:50%;background:' + C.panel + ';',
    'border:1px solid ' + C.line + ';color:' + C.amber + ';font-size:20px;cursor:pointer;',
    'box-shadow:0 4px 18px rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;',
    'font-family:"Courier New",monospace;letter-spacing:-1px;}',
    '#sk-enh-toggle:hover{border-color:' + C.amber + ';}',
    '#sk-enh-panel{position:fixed;z-index:1;background:' + C.panel + ';border:1px solid ' + C.line + ';border-radius:6px;',
    'box-shadow:0 12px 40px rgba(0,0,0,.6);display:flex;flex-direction:column;overflow:hidden;}',
    '#sk-enh-head{display:flex;align-items:center;justify-content:space-between;',
    'padding:10px 12px;border-bottom:1px solid ' + C.line + ';background:' + C.panel2 + ';',
    'cursor:move;user-select:none;touch-action:none;}',
    '#sk-enh-head .brand{font-family:"Courier New",monospace;font-size:12px;color:' + C.dim + ';letter-spacing:1px;}',
    '#sk-enh-head .brand b{color:' + C.amber + ';}',
    '.sk-icon-btn{width:24px;height:24px;border-radius:5px;border:1px solid ' + C.line + ';',
    'background:transparent;color:' + C.dim + ';display:flex;align-items:center;justify-content:center;',
    'cursor:pointer;font-size:13px;line-height:1;padding:0;font-family:inherit;}',
    '.sk-icon-btn:hover:not(:disabled){border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-icon-btn.active{background:' + C.amberDim + ';border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-icon-btn:disabled{opacity:.35;cursor:default;}',
    '.sk-toggle-row{display:flex;align-items:center;justify-content:space-between;padding:5px 1px;}',
    '.sk-toggle-label{font-size:12px;color:' + C.text + ';}',
    '.sk-mad-tag{font-size:10px;color:' + C.dim + ';font-weight:normal;font-style:italic;margin-left:2px;}',
    '.sk-dropzone{border:1.5px dashed ' + C.line + ';border-radius:6px;padding:14px 10px;text-align:center;',
      'font-size:12px;color:' + C.dim + ';cursor:pointer;transition:border-color .15s,background .15s,color .15s;}',
    '.sk-dropzone:hover{border-color:' + C.amber + ';color:' + C.text + ';}',
    '.sk-dropzone.is-dragover{border-color:' + C.amber + ';background:' + C.panel2 + ';color:' + C.text + ';}',
    '.sk-section-label{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:' + C.dim + ';',
      'margin:14px 0 8px;padding-top:10px;border-top:1px solid ' + C.line + ';}',
    '.sk-section-label:first-child{margin-top:0;padding-top:0;border-top:none;}',
    '.sk-subpanel{border-left:2px solid ' + C.line + ';padding:8px 0 2px 10px;margin:2px 0 10px;}',
    '.sk-subdivider{border-top:1px solid ' + C.line + ';margin:10px 0;padding-top:10px;}',

    '.sk-toggle-switch{position:relative;width:32px;height:17px;border-radius:9px;flex-shrink:0;',
    'background:' + C.line + ';cursor:pointer;transition:background .15s ease;}',
    '.sk-toggle-switch.active{background:' + C.amberDim + ';}',
    '.sk-toggle-knob{position:absolute;top:2px;left:2px;width:13px;height:13px;border-radius:50%;',
    'background:' + C.dim + ';transition:left .15s ease,background .15s ease;}',
    '.sk-toggle-switch.active .sk-toggle-knob{left:17px;background:' + C.amber + ';}',
    '.sk-resize-corner{position:absolute;width:14px;height:14px;z-index:5;touch-action:none;}',
    '.sk-resize-corner.nw{top:0;left:0;cursor:nwse-resize;}',
    '.sk-resize-corner.ne{top:0;right:0;cursor:nesw-resize;}',
    '.sk-resize-corner.sw{bottom:0;left:0;cursor:nesw-resize;}',
    '#sk-enh-resize-se{position:absolute;right:0;bottom:0;width:16px;height:16px;cursor:nwse-resize;',
    'touch-action:none;z-index:5;background:linear-gradient(135deg,transparent 0 40%,' + C.dim + ' 40% 46%,',
    'transparent 46% 58%,' + C.dim + ' 58% 64%,transparent 64% 100%);opacity:.7;}',
    '#sk-enh-resize-se:hover{opacity:1;}',
    '.sk-resize-edge{position:absolute;z-index:4;touch-action:none;}',
    '.sk-resize-edge.n{top:0;left:14px;right:14px;height:6px;cursor:ns-resize;}',
    '.sk-resize-edge.s{bottom:0;left:14px;right:14px;height:6px;cursor:ns-resize;}',
    '.sk-resize-edge.w{left:0;top:14px;bottom:14px;width:6px;cursor:ew-resize;}',
    '.sk-resize-edge.e{right:0;top:14px;bottom:14px;width:6px;cursor:ew-resize;}',
    '#sk-enh-tabs{display:flex;border-bottom:1px solid ' + C.line + ';}',
    '.sk-tab{flex:1;padding:9px 0;text-align:center;font-size:12px;letter-spacing:.5px;',
    'text-transform:uppercase;cursor:pointer;color:' + C.dim + ';border-bottom:2px solid transparent;}',
    '.sk-tab.active{color:' + C.amber + ';border-bottom-color:' + C.amber + ';}',
    '.sk-body{padding:12px;overflow-y:auto;flex:1;min-height:0;}',
    '.sk-row{display:flex;gap:6px;margin-bottom:8px;}',
    '.sk-input{flex:1;background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';',
    'padding:7px 9px;border-radius:4px;font-size:13px;outline:none;}',
    '.sk-input:focus{border-color:' + C.amber + ';}',
    '.sk-input[type=number]::-webkit-inner-spin-button,',
    '.sk-input[type=number]::-webkit-outer-spin-button{-webkit-appearance:none;margin:0;}',
    '.sk-input[type=number]{-moz-appearance:textfield;}',
    '.sk-select{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';',
    'padding:7px 6px;border-radius:4px;font-size:12px;}',
    '.sk-btn{background:' + C.amberDim + ';border:1px solid ' + C.amber + ';color:' + C.amber + ';',
    'padding:7px 12px;border-radius:4px;font-size:12px;cursor:pointer;white-space:nowrap;}',
    '.sk-btn:hover{background:' + C.amber + ';color:#1a1509;}',
    '.sk-chips{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px;min-height:0;}',
    '.sk-suggest-list{background:' + C.panel + ';border:1px solid ' + C.line + ';border-radius:6px;',
    'margin-bottom:8px;overflow:hidden;}',
    '.sk-suggest-row{display:flex;justify-content:space-between;align-items:center;',
    'padding:8px 10px;border-top:1px solid ' + C.line + ';cursor:pointer;font-size:12px;}',
    '.sk-suggest-row:first-child{border-top:none;}',
    '.sk-suggest-row:hover{background:' + C.panel2 + ';}',
    '.sk-suggest-row.is-artist span:first-child{color:' + C.amber + ';}',
    '.sk-suggest-row.is-copyright span:first-child{color:' + C.link + ';}',
    '.sk-suggest-count{color:' + C.dim + ';font-size:11px;font-family:monospace;}',
    '.sk-chip{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';',
    'font-size:11px;padding:3px 7px;border-radius:20px;display:flex;align-items:center;gap:5px;',
    'font-family:"Courier New",monospace;}',
    '.sk-chip span{cursor:pointer;color:' + C.red + ';font-weight:bold;}',
    // Type 1 = artist/animator, type 3 = copyright/show — the standard
    // Danbooru1/Moebooru tag-type numbering, already relied on elsewhere in
    // this file for the amber animator color; type 3 specifically wasn't
    // re-verified against a live response this time, just following that
    // same well-established convention.
    '.sk-chip.is-artist{border-color:' + C.amberDim + ';color:' + C.amber + ';}',
    '.sk-chip.is-copyright{border-color:' + C.link + ';color:' + C.link + ';}',
    '.sk-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;}',
    '#sk-enh-panel.sk-size-locked .sk-grid{grid-template-columns:repeat(auto-fill,minmax(140px,1fr));}',
    '.sk-card{position:relative;border:1px solid ' + C.line + ';border-radius:4px;overflow:hidden;',
    'aspect-ratio:1/1;background:#000;cursor:pointer;}',
    '.sk-card img,.sk-card video{width:100%;height:100%;object-fit:cover;display:block;opacity:.9;}',
    '.sk-card:hover img,.sk-card:hover video{opacity:1;}',
    '.sk-card video{position:absolute;top:0;left:0;}',
    '.sk-card .score{position:absolute;top:3px;right:4px;background:rgba(0,0,0,.7);',
    'color:' + C.amber + ';font-size:10px;padding:1px 5px;border-radius:8px;z-index:2;',
    'font-family:"Courier New",monospace;}',
    '.sk-card .vidmark{position:absolute;top:3px;left:4px;background:rgba(0,0,0,.7);',
    'color:' + C.text + ';font-size:9px;padding:1px 4px;border-radius:8px;z-index:2;',
    'font-family:"Courier New",monospace;}',
    '.sk-meta{font-size:11px;color:' + C.dim + ';margin:8px 0 4px;font-family:"Courier New",monospace;}',
    '.sk-card .info-badge{position:absolute;bottom:3px;right:4px;background:rgba(0,0,0,.7);',
    'color:' + C.text + ';font-size:11px;width:18px;height:18px;border-radius:50%;',
    'display:flex;align-items:center;justify-content:center;z-index:2;cursor:pointer;',
    'font-family:"Courier New",monospace;}',
    '.sk-card .info-badge:hover{background:rgba(0,0,0,.9);color:' + C.amber + ';}',
    '.sk-card .remove-badge{position:absolute;bottom:3px;left:4px;background:rgba(0,0,0,.7);',
    'color:' + C.text + ';font-size:13px;width:18px;height:18px;border-radius:50%;',
    'display:flex;align-items:center;justify-content:center;z-index:2;cursor:pointer;',
    'font-family:"Courier New",monospace;line-height:1;}',
    '.sk-card .remove-badge:hover{background:' + C.red + ';color:#fff;}',
    '.sk-info-popup{position:fixed;z-index:2147483300;width:280px;max-height:320px;',
    'overflow-y:auto;background:' + C.bg + ';border:1px solid ' + C.line + ';border-radius:6px;',
    'box-shadow:0 10px 30px rgba(0,0,0,.6);}',
    '.sk-info-popup .sk-dock-head{padding-right:26px;}',
    '.sk-info-popup .sk-close{position:absolute;top:6px;right:8px;}',
    '.sk-dock-head{display:flex;align-items:center;justify-content:space-between;',
    'padding:8px 10px;background:' + C.panel2 + ';border-bottom:1px solid ' + C.line + ';}',
    '.sk-dock-badges{display:flex;gap:6px;align-items:center;}',
    '.sk-badge{font-family:"Courier New",monospace;font-size:11px;padding:2px 7px;',
    'border-radius:10px;background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';}',
    '.sk-badge.score{color:' + C.amber + ';border-color:' + C.amberDim + ';}',
    '.sk-stars{display:inline-flex;gap:2px;align-items:center;}',
    '.sk-star{font-size:15px;color:' + C.dim + ';cursor:pointer;line-height:1;}',
    '.sk-star.filled{color:' + C.amber + ';}',
    '.sk-star-clear{font-size:12px;color:' + C.dim + ';cursor:pointer;margin-left:3px;opacity:.3;}',
    '.sk-star-clear.active{opacity:.8;}',
    '.sk-star-clear:hover{color:' + C.red + ';opacity:1;}',
    '.sk-dock-head a{font-size:11px;color:' + C.amber + ';text-decoration:none;',
    'border:1px solid ' + C.amberDim + ';padding:2px 8px;border-radius:10px;}',
    '.sk-dock-head a:hover{background:' + C.amberDim + ';}',
    '.sk-dock-body{padding:10px;}',
    '.sk-dock-section + .sk-dock-section{margin-top:9px;}',
    '.sk-tagblock-label{color:' + C.dim + ';font-size:10px;text-transform:uppercase;',
    'letter-spacing:.6px;margin:0 0 5px;display:flex;align-items:center;gap:5px;}',
    '.sk-tagblock-label:before{content:"";width:3px;height:3px;border-radius:50%;',
    'background:' + C.dim + ';display:inline-block;}',
    '.sk-chipwrap{display:flex;flex-wrap:wrap;gap:5px;max-height:110px;overflow-y:auto;}',
    '.sk-mini-chip{display:inline-block;font-size:10px;padding:3px 8px;border-radius:10px;',
    'margin:0 4px 4px 0;font-family:"Courier New",monospace;border:1px solid ' + C.line + ';',
    'background:' + C.panel2 + ';}',
    '.sk-mini-chip.artist{background:' + C.amberDim + ';border-color:' + C.amber + ';color:' + C.amber + ';font-weight:bold;}',
    '.sk-mini-chip.other{color:' + C.dim + ';}',
    '.sk-mini-chip.show{color:' + C.link + ';}',
    '.sk-mini-chip.clickable{cursor:pointer;}',
    '.sk-mini-chip.clickable:hover{border-color:' + C.amber + ';}',
    '.sk-facet-item{display:flex;align-items:center;gap:5px;font-size:11px;padding:4px 2px;',
    'border-radius:3px;cursor:pointer;color:' + C.text + ';min-width:0;}',
    '.sk-facet-item:hover{background:' + C.panel2 + ';}',
    '.sk-facet-item.off{color:' + C.dim + ';text-decoration:line-through;opacity:.6;}',
    '.sk-facet-item input{accent-color:' + C.amber + ';flex-shrink:0;width:13px;height:13px;margin:0;}',
    '.sk-facet-item .fname{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;',
    'font-family:"Courier New",monospace;}',
    '.sk-facet-item .fcount{flex-shrink:0;color:' + C.dim + ';font-family:"Courier New",monospace;font-size:10px;}',
    '.sk-facet-item.is-artist .fname{color:' + C.amber + ';font-weight:bold;}',
    '.sk-filter-toggle{display:inline-flex;align-items:center;gap:6px;background:transparent;',
    'border:1px solid ' + C.line + ';color:' + C.text + ';padding:4px 10px;border-radius:14px;',
    'font-size:11px;cursor:pointer;font-family:inherit;}',
    '.sk-filter-toggle:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-filter-toggle .chev{font-size:8px;color:' + C.dim + ';transition:transform .15s ease;}',
    '.sk-filter-toggle.open .chev{transform:rotate(180deg);}',
    '.sk-filter-badge{background:' + C.amberDim + ';color:' + C.amber + ';border-radius:8px;',
    'padding:0 6px;font-family:"Courier New",monospace;font-size:10px;line-height:1.5;}',
    '.sk-mode-row{display:flex;gap:6px;margin-bottom:10px;}',
    '.sk-mode-btn{flex:1;background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.dim + ';',
    'padding:7px 6px;border-radius:5px;font-size:11px;cursor:pointer;font-family:inherit;',
    'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
    '.sk-mode-btn:hover{border-color:' + C.amber + ';}',
    '.sk-mode-btn.active{background:' + C.amberDim + ';border-color:' + C.amber + ';color:' + C.amber + ';font-weight:bold;}',
    '.sk-facet-grid{border:1px solid ' + C.line + ';border-radius:6px;padding:8px 8px 6px;',
    'margin:-2px 0 8px;background:' + C.bg + ';',
    'display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:2px 10px;',
    'max-height:220px;overflow-y:auto;overflow-x:hidden;}',
    '.sk-caption{color:' + C.dim + ';font-size:10.5px;line-height:1.5;margin-bottom:10px;}',
    '.sk-show-pick{display:flex;justify-content:space-between;align-items:center;padding:8px 9px;',
    'border:1px solid ' + C.line + ';border-radius:5px;margin-bottom:5px;cursor:pointer;}',
    '.sk-show-pick:hover{border-color:' + C.amber + ';background:' + C.panel2 + ';}',
    '.sk-show-pick .name{font-family:"Courier New",monospace;font-size:12px;}',
    '.sk-show-pick .cnt{color:' + C.dim + ';font-size:11px;}',
    '.sk-show-pick.off{opacity:.5;cursor:default;}',
    '.sk-show-pick.off:hover{border-color:' + C.line + ';background:none;}',
    '.sk-show-head{display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap;}',
    '.sk-mini-toggle{background:transparent;border:1px solid ' + C.line + ';color:' + C.dim + ';',
    'padding:3px 9px;border-radius:12px;font-size:10px;cursor:pointer;font-family:inherit;white-space:nowrap;}',
    '.sk-mini-toggle:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-show-head .title{font-size:15px;color:' + C.amber + ';font-family:"Courier New",monospace;}',
    '.sk-show-head a{font-size:11px;color:' + C.dim + ';text-decoration:none;}',
    '.sk-show-head a:hover{color:' + C.amber + ';}',
    '.sk-show-nav{display:flex;align-items:center;justify-content:space-between;gap:6px;margin-bottom:10px;}',
    '.sk-freq-list{border:1px solid ' + C.line + ';border-radius:8px;padding:10px 12px 6px;',
    'background:linear-gradient(180deg,' + C.panel2 + ',' + C.panel + ');}',
    '.sk-freq-row{display:flex;align-items:center;gap:8px;padding:4px 2px;border-radius:5px;cursor:pointer;',
    'transition:background .12s ease;}',
    '.sk-freq-row:hover{background:rgba(255,176,32,.08);}',
    '.sk-freq-row.is-show:hover{background:rgba(109,179,242,.08);}',
    '.sk-freq-rank{width:14px;flex-shrink:0;font-size:10px;color:' + C.dim + ';text-align:right;font-family:"Courier New",monospace;}',
    '.sk-freq-name{width:112px;flex-shrink:0;font-size:12px;color:' + C.amber + ';white-space:nowrap;',
    'overflow:hidden;text-overflow:ellipsis;}',
    '.sk-freq-row.is-show .sk-freq-name{color:' + C.link + ';}',
    '.sk-freq-bar-wrap{flex:1;height:6px;border-radius:3px;background:' + C.bg + ';overflow:hidden;}',
    '.sk-freq-bar{height:100%;border-radius:3px;background:linear-gradient(90deg,' + C.amberDim + ',' + C.amber + ');}',
    '.sk-freq-row.is-show .sk-freq-bar{background:linear-gradient(90deg,#2c5170,' + C.link + ');}',
    '.sk-freq-count{width:34px;flex-shrink:0;text-align:right;font-size:11px;color:' + C.dim + ';',
    'font-family:"Courier New",monospace;}',
    '.sk-nav-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';',
    'padding:5px 10px;border-radius:14px;font-size:11px;cursor:pointer;font-family:inherit;white-space:nowrap;}',
    '.sk-nav-btn:hover:not(:disabled){border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-nav-btn:disabled{opacity:.35;cursor:default;}',
    '.sk-nav-crumb{flex:1;text-align:center;font-size:11px;color:' + C.dim + ';font-family:"Courier New",monospace;',
    'overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-related-row{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:12px;}',
    '.sk-chip.clickable{cursor:pointer;}',
    '.sk-chip.clickable:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-ep-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;}',
    '.sk-ep-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';border-radius:5px;',
    'padding:8px 4px;text-align:center;cursor:pointer;}',
    '.sk-ep-btn:hover{border-color:' + C.amber + ';}',
    '.sk-ep-btn .num{display:block;font-family:"Courier New",monospace;color:' + C.amber + ';',
    'font-size:13px;font-weight:bold;}',
    '.sk-ep-btn .cnt{display:block;font-size:10px;color:' + C.dim + ';margin-top:2px;}',
    '.sk-stat-big{font-size:34px;color:' + C.amber + ';font-family:"Courier New",monospace;',
    'font-weight:bold;line-height:1;}',
    '.sk-stat-label{font-size:11px;color:' + C.dim + ';text-transform:uppercase;letter-spacing:.5px;margin-top:2px;}',
    '.sk-stat-block{display:flex;gap:22px;margin:6px 0 14px;}',
    '.sk-taglist{display:flex;flex-direction:column;gap:5px;}',
    '.sk-tagrow{display:flex;align-items:center;gap:8px;font-size:12px;}',
    '.sk-tagrow .name{width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:' + C.text + ';}',
    '.sk-tagrow .bar{flex:1;height:6px;background:' + C.bg + ';border-radius:3px;overflow:hidden;}',
    '.sk-tagrow .bar i{display:block;height:100%;background:' + C.amber + ';}',
    '.sk-tagrow .n{width:28px;text-align:right;color:' + C.dim + ';font-family:"Courier New",monospace;font-size:11px;}',
    '.sk-filmstrip{display:flex;align-items:flex-end;gap:2px;height:70px;margin:10px 0 4px;',
    'border-bottom:1px solid ' + C.line + ';padding-bottom:2px;}',
    '.sk-frame{flex:1;background:' + C.amberDim + ';border-radius:1px 1px 0 0;min-height:2px;position:relative;}',
    '.sk-frame:hover{background:' + C.amber + ';}',
    '.sk-frame .yr{position:absolute;bottom:-16px;left:0;right:0;text-align:center;',
    'font-size:9px;color:' + C.dim + ';font-family:"Courier New",monospace;}',
    '.sk-frame .ct{position:absolute;top:-15px;left:0;right:0;text-align:center;',
    'font-size:9px;color:' + C.amber + ';font-family:"Courier New",monospace;opacity:0;}',
    '.sk-frame:hover .ct{opacity:1;}',
    '.sk-empty{color:' + C.dim + ';font-size:12px;text-align:center;padding:20px 0;}',
    '.sk-loading{color:' + C.amber + ';font-size:12px;text-align:center;padding:20px 0;',
    'font-family:"Courier New",monospace;}',
    '.sk-xc-box{max-width:1120px;height:min(90vh,800px);max-height:none;display:flex;flex-direction:column;overflow:hidden;',
    'font-family:"Neue Haas Grotesk","Helvetica Neue",Arial,sans-serif;color:' + C.text + ';}',
    '.sk-xc-box button,.sk-xc-box input,.sk-xc-box select{font-family:inherit;}',
    '.sk-xc-title{font-size:13px;color:' + C.text + ';}',
    '.sk-xc-title span{color:' + C.dim + ';margin-left:6px;}',
    '.sk-xc-body{flex:1;min-height:0;display:grid;grid-template-columns:minmax(0,1.5fr) minmax(300px,1fr);}',
    '.sk-xc-left{overflow-y:auto;padding:14px 16px;border-right:1px solid ' + C.line + ';min-height:0;}',
    '.sk-xc-right{display:flex;flex-direction:column;min-height:0;}',
    '.sk-xc-stage{display:flex;align-items:center;justify-content:center;background:' + C.bg + ';border:1px solid ' + C.line + ';border-radius:6px;padding:10px;box-sizing:border-box;}',
    '.sk-xc-canvas{position:relative;background:#000;flex-shrink:0;overflow:hidden;}',
    '.sk-xc-cell{position:absolute;box-sizing:border-box;border:1px solid #000;overflow:hidden;cursor:grab;touch-action:none;background:#1a1a1a;',
    'transition:left .18s ease,top .18s ease,width .18s ease,height .18s ease;}',
    '.sk-xc-cell.ph{outline:2px dashed ' + C.amber + ';outline-offset:-2px;}',
    '.sk-xc-cell.ph img,.sk-xc-cell.ph .sk-xc-lblwrap{opacity:.3;}',
    '.sk-xc-box .sk-xc-cell img{max-height:none;position:absolute;inset:0;width:100%;height:100%;object-fit:cover;display:block;background:transparent;}',
    '.sk-xc-cell.hl{outline:2px solid ' + C.amber + ';outline-offset:-2px;z-index:1;}',
    '.sk-xc-num{position:absolute;top:3px;right:4px;font:10px "Courier New",monospace;color:' + C.text + ';background:rgba(0,0,0,.6);padding:0 4px;border-radius:2px;}',
    '.sk-xc-lblwrap{position:absolute;pointer-events:none;}',
    '.sk-xc-chip{position:absolute;white-space:pre;color:#fff;font-family:Arial,Helvetica,sans-serif;pointer-events:auto;cursor:grab;touch-action:none;user-select:none;}',
    '.sk-xc-chip:hover{outline:1px dashed ' + C.amber + ';}',
    '.sk-xc-ghost{position:fixed !important;margin:0;z-index:2147483647;pointer-events:none;box-sizing:border-box;box-shadow:0 14px 32px rgba(0,0,0,.7);transform:scale(1.05);transition:none;}',
    '.sk-xc-ghost.settling{transition:left .18s ease,top .18s ease,width .18s ease,height .18s ease,transform .18s ease,box-shadow .18s ease;transform:none;box-shadow:none;}',
    '.sk-xc-ghost.sk-xc-rowhead{background:' + C.panel2 + ';border:1px solid ' + C.amber + ';border-radius:6px;}',
    '.xc-dragging,.xc-dragging *{cursor:grabbing !important;}',
    '.sk-xc-film{flex-wrap:wrap;gap:6px;margin-top:8px;}',
    '.sk-xc-fr{position:relative;width:72px;height:41px;box-sizing:border-box;border:1px solid ' + C.line + ';border-radius:3px;overflow:hidden;cursor:grab;touch-action:none;background:#000;}',
    '.sk-xc-film.port .sk-xc-fr{width:36px;height:64px;}',
    '.sk-xc-fr:hover{border-color:' + C.dim + ';}',
    '.sk-xc-fr.on{border-color:' + C.amber + ';box-shadow:0 0 0 1px ' + C.amber + ';}',
    '.sk-xc-fr.ph{opacity:.3;}',
    '.sk-xc-box .sk-xc-fr img{width:100%;height:100%;max-height:none;object-fit:cover;display:block;pointer-events:none;}',
    '.sk-xc-frn{position:absolute;left:2px;top:1px;font:9px "Courier New",monospace;color:' + C.text + ';background:rgba(0,0,0,.6);padding:0 3px;border-radius:2px;}',
    '.sk-xc-hint{min-height:16px;margin:6px 2px 0;font-size:11px;color:' + C.dim + ';}',
    '.sk-xc-pos{display:inline-grid;grid-template-columns:repeat(3,20px);gap:3px;padding:4px;border:1px solid ' + C.line + ';border-radius:5px;background:' + C.bg + ';}',
    '.sk-xc-pos button{width:20px;height:12px;padding:0;border:1px solid ' + C.line + ';border-radius:2px;background:transparent;cursor:pointer;}',
    '.sk-xc-pos button:hover{border-color:' + C.amber + ';}',
    '.sk-xc-pos button.on{background:' + C.amber + ';border-color:' + C.amber + ';}',
    '.sk-xc-poshint{font-size:11px;color:' + C.dim + ';}',
    '.sk-xc-chip::after{content:"";position:absolute;inset:-6px;}',
    '.sk-xc-hint a{color:' + C.amber + ';}',
    '.sk-xc-set{margin-top:12px;border-top:1px solid ' + C.line + ';padding-top:8px;}',
    '.sk-xc-line{display:flex;align-items:center;flex-wrap:wrap;gap:6px 8px;padding:5px 0;}',
    '.sk-xc-line .k{width:108px;flex-shrink:0;font-size:12px;color:' + C.dim + ';}',
    '.sk-xc-seg{display:inline-flex;border:1px solid ' + C.line + ';border-radius:5px;overflow:hidden;}',
    '.sk-xc-seg button{background:transparent;border:0;color:' + C.dim + ';padding:4px 10px;font-size:12px;cursor:pointer;font-family:inherit;}',
    '.sk-xc-seg button+button{border-left:1px solid ' + C.line + ';}',
    '.sk-xc-seg button:hover{color:' + C.text + ';}',
    '.sk-xc-seg button.on{background:' + C.amberDim + ';color:' + C.amber + ';}',
    '.sk-xc-seg.dis{opacity:.4;pointer-events:none;}',
    '#xc-music-line{border:1px dashed transparent;border-radius:6px;}',
    '#xc-music-line.is-dragover{border-color:' + C.amber + ';background:' + C.panel2 + ';}',
    '.sk-xc-tracks{display:inline-flex;flex-wrap:wrap;gap:4px;}',
    '.sk-xc-track{display:inline-flex;align-items:center;gap:6px;max-width:170px;padding:2px 8px;border:1px solid ' + C.line + ';border-radius:10px;font-size:11px;color:' + C.text + ';}',
    '.sk-xc-track .nm{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-xc-cap{margin:0 0 0 116px;font-size:11px;color:' + C.dim + ';}',
    '.sk-xc-cap:empty{display:none;}',
    '.sk-xc-listhead{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px 12px;border-bottom:1px solid ' + C.line + ';font-size:12px;color:' + C.text + ';}',
    '.sk-xc-listhead b{font-weight:normal;color:' + C.dim + ';}',
    '.sk-xc-list{flex:1;min-height:0;overflow-y:auto;position:relative;}',
    '.sk-xc-row.ph{background:' + C.panel2 + ';outline:1px dashed ' + C.amber + ';outline-offset:-3px;}',
    '.sk-xc-row.ph>*{opacity:.3;}',
    '.sk-xc-row{border-bottom:1px solid ' + C.line + ';}',
    '.sk-xc-row.open{background:' + C.panel2 + ';}',
    '.sk-xc-row.dragging{opacity:.55;background:' + C.panel2 + ';}',
    '.sk-xc-rowhead{display:flex;align-items:center;gap:8px;padding:7px 12px;min-height:46px;box-sizing:border-box;cursor:grab;user-select:nonetouch-action:pan-y;}',
    '.sk-xc-rowhead:hover .sk-xc-name{color:' + C.amber + ';}',
    '.sk-xc-grip{cursor:grab;color:' + C.dim + ';font-size:12px;letter-spacing:-2px;line-height:1;touch-action:none;user-select:none;padding:2px 2px;border-radius:3px;}',
    '.sk-xc-grip:hover,.sk-xc-grip:focus{color:' + C.amber + ';outline:none;}',
    '.sk-xc-n{width:14px;text-align:right;font:11px "Courier New",monospace;color:' + C.dim + ';flex-shrink:0;}',
    '.sk-xc-box .sk-xc-rowhead img{width:44px;height:25px;max-height:none;object-fit:cover;border-radius:2px;background:#000;flex-shrink:0;}',
    '.sk-xc-who{flex:1;min-width:0;display:flex;flex-direction:column;gap:1px;}',
    '.sk-xc-name{font-size:12px;color:' + C.text + ';overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-xc-sub{font-size:10px;color:' + C.dim + ';overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.sk-xc-sub .id{font-family:"Courier New",monospace;}',
    '.sk-xc-row.hl:not(.open){background:' + C.panel2 + ';}',
    '.sk-xc-badge{font-size:10px;color:' + C.amber + ';white-space:nowrap;}',
    '.sk-xc-badge:empty{display:none;}',
    '.sk-xc-chev{color:' + C.dim + ';font-size:10px;width:10px;text-align:center;}',
    '.sk-xc-edit{padding:2px 12px 10px 34px;}',
    '.sk-xc-field{display:flex;align-items:center;gap:6px;padding:3px 0;}',
    '.sk-xc-field .k{width:40px;flex-shrink:0;font-size:11px;color:' + C.dim + ';}',
    '.sk-xc-field .dash{color:' + C.dim + ';}',
    '.sk-xc-field .sk-input{min-width:0;font-size:12px;padding:4px 6px;}',
    '.sk-xc-field input[data-s],.sk-xc-field input[data-e]{flex:0 1 96px;}',
    '.sk-xc-actions{display:flex;gap:6px;justify-content:flex-end;padding-top:4px;}',
    '.sk-xc-foot{display:flex;align-items:center;gap:8px;padding:10px 14px;border-top:1px solid ' + C.line + ';background:' + C.panel2 + ';}',
    '.sk-xc-sum{flex:1;min-width:0;font-size:12px;color:' + C.dim + ';}',
    '@media (max-width:760px){.sk-xc-box{height:92vh;}.sk-xc-body{display:block;overflow-y:auto;}.sk-xc-left{overflow:visible;border-right:0;}.sk-xc-list{overflow:visible;}}',
    '.sk-spinner{display:inline-block;width:12px;height:12px;border:2px solid ' + C.line + ';',
    'border-top-color:' + C.amber + ';border-radius:50%;vertical-align:middle;margin-right:6px;',
    'animation:sk-spin .7s linear infinite;}',
    '@keyframes sk-spin{to{transform:rotate(360deg);}}',
    '.sk-progress{height:4px;background:' + C.line + ';border-radius:2px;margin-top:6px;overflow:hidden;position:relative;}',
    '.sk-progress-fill{height:100%;width:0;background:' + C.amber + ';border-radius:2px;transition:width .25s linear;}',
    '.sk-progress.ind .sk-progress-fill{position:absolute;width:35%;transition:none;animation:sk-ind 1.2s ease-in-out infinite;}',
    '@keyframes sk-ind{0%{left:-35%;}100%{left:100%;}}',
    '.sk-st-pct{margin-left:6px;opacity:.75;}',
    '.sk-close{cursor:pointer;color:' + C.dim + ';font-size:16px;line-height:1;}',
    '.sk-media-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:2147483600;',
    'display:flex;align-items:center;justify-content:center;padding:24px;}',
    '.sk-media-box{max-width:760px;width:100%;max-height:90vh;background:' + C.panel + ';border:1px solid ' + C.line + ';',
    'border-radius:8px;overflow-y:auto;overflow-x:hidden;box-shadow:0 20px 60px rgba(0,0,0,.6);}',
    '.sk-media-box video,.sk-media-box img{width:100%;max-height:72vh;display:block;background:#000;',
    'object-fit:contain;}',
    '.sk-media-top{position:sticky;top:0;z-index:1;display:flex;align-items:center;gap:8px;padding:8px 10px;background:' + C.panel2 + ';}',
    '.sk-media-viewpost{margin-left:auto;color:' + C.amber + ';font-size:12px;text-decoration:none;',
    'font-family:"Courier New",monospace;}',
    '.sk-media-viewpost:hover{text-decoration:underline;}',
    '.sk-media-close{cursor:pointer;color:' + C.dim + ';font-size:22px;line-height:1;padding:0 2px 2px;}',
    '.sk-login-box{width:100%;max-width:320px;background:' + C.panel + ';border:1px solid ' + C.line + ';',
    'border-radius:8px;padding:18px;box-shadow:0 20px 60px rgba(0,0,0,.6);}',
    '.sk-login-title{font-size:15px;font-weight:bold;color:' + C.text + ';margin-bottom:12px;}',
    '.sk-login-box .sk-input{width:100%;margin-bottom:8px;}',
    '.sk-login-cancel{display:block;text-align:center;margin-top:10px;color:' + C.dim + ';font-size:12px;cursor:pointer;}',
    '.sk-comment-composer{background:' + C.panel2 + ';border:1px solid ' + C.line + ';border-radius:6px;',
    'padding:8px;margin-bottom:10px;}',
    '.sk-comment-loggedin{display:flex;justify-content:space-between;font-size:11px;color:' + C.dim + ';margin-bottom:6px;}',
    '.sk-comment-logout{color:' + C.red + ';cursor:pointer;}',
    '.sk-comment-textarea{width:100%;background:' + C.bg + ';border:1px solid ' + C.line + ';border-radius:6px;',
    'color:' + C.text + ';padding:6px;font-size:12px;min-height:50px;resize:vertical;margin-bottom:6px;',
    'font-family:inherit;}',
    '.sk-comment-loginlink{color:' + C.amber + ';font-size:12px;font-weight:600;cursor:pointer;margin-bottom:10px;display:inline-block;}',
    '.sk-media-close:hover{color:' + C.red + ';}',
    '.sk-frame-bar{padding:8px 10px;background:' + C.panel2 + ';border-top:1px solid ' + C.line + ';}',
    '.sk-frame-row{display:flex;align-items:center;gap:4px;}',
    '.sk-frame-btn{background:' + C.bg + ';border:1px solid ' + C.line + ';color:' + C.text + ';',
    'padding:5px 9px;border-radius:5px;font-size:13px;cursor:pointer;font-family:inherit;white-space:nowrap;}',
    '.sk-frame-btn:hover{border-color:' + C.amber + ';color:' + C.amber + ';}',
    '.sk-frame-count{flex:1;text-align:center;font-size:13px;font-weight:bold;color:' + C.amber + ';',
    'font-family:"Courier New",monospace;}',
    '.sk-frame-time{text-align:center;font-size:11px;color:' + C.dim + ';margin-top:5px;',
    'font-family:"Courier New",monospace;}',
    '.sk-trim-row{display:flex;align-items:center;gap:6px;padding:8px 10px 0;flex-wrap:wrap;}',
    '.sk-trim-label{font-size:10px;color:' + C.dim + ';font-family:"Courier New",monospace;}',
    '.sk-action-row{display:flex;gap:6px;padding:8px 10px;}',
    '.sk-action-row .sk-frame-btn{flex:1;}',
    '.sk-frame-btn:disabled{opacity:.35;cursor:default;}',
    '.sk-frame-btn:disabled:hover{border-color:' + C.line + ';color:' + C.text + ';}',
    '.sk-action-status{padding:0 10px 8px;font-size:11px;color:' + C.amber + ';',
    'font-family:"Courier New",monospace;min-height:14px;}',
    '.sk-load-more-wrap{text-align:center;margin-top:10px;}',
    '.sk-load-more-wrap .sk-frame-btn{display:inline-block;padding:8px 16px;}',
    '.sk-comments-row{padding:0 10px 8px;border-top:1px solid ' + C.line + ';padding-top:8px;}',
    '.sk-comments-panel{max-height:220px;overflow-y:auto;padding:0 10px 10px;}',
    '.sk-comment{padding:8px 0;border-top:1px solid ' + C.line + ';}',
    '.sk-comment:first-child{border-top:none;}',
    '.sk-comment-head{display:flex;justify-content:space-between;font-size:11px;color:' + C.amber + ';',
    'font-family:"Courier New",monospace;margin-bottom:3px;}',
    '.sk-comment-head span{color:' + C.dim + ';font-weight:normal;}',
    '.sk-comment-body{font-size:12px;color:' + C.text + ';line-height:1.5;white-space:pre-wrap;}',
    '.sk-comment-quote{border-left:3px solid ' + C.line + ';padding:4px 0 4px 8px;margin:4px 0;color:' + C.dim + ';}',
    '.sk-comment-ts{color:' + C.amber + ';cursor:pointer;font-weight:bold;}',
    '.sk-comment-ts:hover{text-decoration:underline;}',
    '.sk-comment-postlink{color:' + C.link + ';cursor:pointer;text-decoration:underline;}',
    '.sk-comment-link{color:' + C.link + ';text-decoration:underline;}',
    '.sk-close:hover{color:' + C.red + ';}',
    // Themed scrollbars for our own scrollable panels — scoped to these specific
    // classes only, since these styles are injected globally into the host page
    // and a broader selector would restyle sakugabooru's own scrollbars too.
    '.sk-body,.sk-comments-panel,.sk-facet-grid,.sk-chipwrap,.sk-media-box{',
    'scrollbar-width:thin;scrollbar-color:' + C.amberDim + ' ' + C.bg + ';}',
    '.sk-body::-webkit-scrollbar,.sk-comments-panel::-webkit-scrollbar,',
    '.sk-facet-grid::-webkit-scrollbar,.sk-chipwrap::-webkit-scrollbar,',
    '.sk-media-box::-webkit-scrollbar{width:8px;}',
    '.sk-body::-webkit-scrollbar-track,.sk-comments-panel::-webkit-scrollbar-track,',
    '.sk-facet-grid::-webkit-scrollbar-track,.sk-chipwrap::-webkit-scrollbar-track,',
    '.sk-media-box::-webkit-scrollbar-track{background:' + C.bg + ';}',
    '.sk-body::-webkit-scrollbar-thumb,.sk-comments-panel::-webkit-scrollbar-thumb,',
    '.sk-facet-grid::-webkit-scrollbar-thumb,.sk-chipwrap::-webkit-scrollbar-thumb,',
    '.sk-media-box::-webkit-scrollbar-thumb{background:' + C.amberDim + ';border-radius:4px;}',
    '.sk-body::-webkit-scrollbar-thumb:hover,.sk-comments-panel::-webkit-scrollbar-thumb:hover,',
    '.sk-facet-grid::-webkit-scrollbar-thumb:hover,.sk-chipwrap::-webkit-scrollbar-thumb:hover,',
    '.sk-media-box::-webkit-scrollbar-thumb:hover{background:' + C.amber + ';}',
    // ===== Shape and spacing system =====
    // One set of rules for every screen, so nothing is its own special case:
    //   shapes   controls (buttons, inputs, selects, icon buttons, chips, tags) share one
    //            corner radius; containers (panels, cards, popups, modals, lists) share a
    //            slightly larger one; overlay labels and thumbnails use a small one.
    //            Circles are only for things that are actually round (switch knob, round badges).
    //   sizes    regular controls are 28px tall, small ones (header icons, toggles, chips) 24px.
    //   spacing  a 4px grid: 4 inside tight groups, 8 between neighbours and rows, 12 between sections.
    // Change the numbers in the three variables above the style list to retune everything at once.
    '.sk-input,.sk-select,.sk-btn,.sk-mode-btn,.sk-frame-btn,.sk-nav-btn,.sk-ep-btn,.sk-comment-textarea,.sk-seg,.sk-xc-seg,.sk-icon-btn,',
    '.sk-filter-toggle,.sk-mini-toggle,.sk-chip,.sk-mini-chip,.sk-xc-track,.sk-dock-head a,.sk-xc-pos button{border-radius:' + R_CTL + ';}',
    '#sk-enh-panel,.sk-media-box,.sk-login-box,.sk-info-popup,.sk-suggest-list,.sk-card,.sk-facet-grid,.sk-freq-list,.sk-dropzone,',
    '.sk-show-pick,.sk-xc-stage,.sk-xc-pos,.sk-comment-composer,#xc-music-line,.sk-xc-ghost.sk-xc-rowhead{border-radius:' + R_BOX + ';}',
    '.sk-badge,.sk-filter-badge,.sk-card .score,.sk-card .vidmark,.sk-xc-num,.sk-xc-frn,.sk-xc-fr,.sk-facet-item,.sk-freq-row,.sk-xc-grip,',
    '.sk-xc-box .sk-xc-rowhead img,.sk-media-box::-webkit-scrollbar-thumb{border-radius:' + R_INNER + ';}',
    '.sk-input,.sk-select,.sk-btn,.sk-mode-btn,.sk-frame-btn,.sk-nav-btn{box-sizing:border-box;min-height:' + H_CTL + ';}',
    '.sk-btn,.sk-mode-btn,.sk-frame-btn,.sk-nav-btn{display:inline-flex;align-items:center;justify-content:center;}',
    '.sk-input{padding:4px 10px;}',
    '.sk-select{padding:4px 8px;}',
    '.sk-btn{padding:4px 14px;}',
    '.sk-nav-btn{padding:4px 12px;font-size:12px;}',
    '.sk-frame-btn{padding:4px 10px;}',
    '.sk-mode-btn{flex:0 0 auto;padding:4px 12px;font-size:12px;}',
    '.sk-icon-btn,.sk-filter-toggle,.sk-mini-toggle{box-sizing:border-box;height:' + H_SM + ';}',
    '.sk-filter-toggle,.sk-mini-toggle{display:inline-flex;align-items:center;padding:0 10px;font-size:11px;}',
    '.sk-chip{padding:3px 8px;font-size:11px;}',
    '.sk-mini-chip{padding:3px 8px;}',
    // spacing: 8 between rows and neighbours, 12 between sections
    '.sk-row{gap:8px;margin-bottom:8px;}',
    '.sk-chips{gap:6px;margin-bottom:8px;}',
    '.sk-chips:empty,#sk-show-animators-wrap:empty{display:none;}',
    '.sk-mode-row{gap:8px;margin-bottom:8px;}',
    '.sk-meta{margin:0 0 8px;}',
    '.sk-facet-grid{margin:0 0 8px;}',
    '.sk-grid,.sk-ep-grid{gap:8px;}',
    '.sk-caption{margin-bottom:8px;}',
    '.sk-show-nav{gap:8px;margin-bottom:8px;}',
    '.sk-show-head{gap:8px;margin-bottom:8px;}',
    '.sk-related-row{gap:6px;margin-bottom:8px;}',
    '.sk-show-pick{padding:8px 10px;margin-bottom:6px;}',
    '.sk-load-more-wrap{margin-top:12px;}',
    '.sk-tab{padding:8px 0;}',
    '.sk-body{padding:12px;}',
    // clip viewer: credits (animator + tags) live in their own panel to the left of the viewer
    '.sk-media-backdrop.sk-clip-split{gap:12px;align-items:flex-start;}',
    '.sk-clip-split .sk-media-box{flex:1 1 760px;min-width:0;width:auto;max-width:760px;}',
    '.sk-clip-side{flex:0 0 auto;width:max-content;min-width:180px;max-width:min(320px,32vw);max-height:90vh;overflow-x:hidden;overflow-y:auto;box-sizing:border-box;padding:12px;',
    'background:' + C.panel + ';border:1px solid ' + C.line + ';border-radius:' + R_BOX + ';box-shadow:0 20px 60px rgba(0,0,0,.6);}',
    '.sk-clip-side .sk-dock-section + .sk-dock-section{margin-top:16px;}',
    '.sk-clip-side .sk-tagblock-label{font-size:11px;margin-bottom:8px;}',
    '.sk-clip-side .sk-chipwrap{max-height:none;overflow:visible;gap:6px;min-width:0;}',
    '.sk-clip-side .sk-mini-chip{font-family:inherit;font-size:13px;line-height:18px;padding:4px 10px;margin:0;max-width:100%;box-sizing:border-box;white-space:normal;overflow-wrap:anywhere;}',
    '.sk-clip-side .sk-mini-chip.artist{font-size:14px;padding:5px 12px;}',
    '.sk-media-top{flex-wrap:wrap;}',
    '.sk-media-top .sk-media-viewpost{white-space:nowrap;}',
    '@media (max-width:900px){',
      '.sk-media-backdrop.sk-clip-split{flex-direction:column;align-items:center;justify-content:flex-start;overflow-y:auto;}',
      '.sk-clip-side{flex:0 0 auto;width:100%;min-width:0;max-width:760px;max-height:none;}',
      '.sk-clip-split .sk-media-box{flex:0 0 auto;width:100%;max-height:none;}',
    '}'
  ].join('');

